### PR TITLE
Location of `mypaint.iss.in` moved to `/windows/innosetup/`

### PR DESCRIPTION
**Pull request by daleathan**
Location of `mypaint.iss.in` moved to `/windows/innosetup/`

### CODE REVIEW

**Comment by odysseywestra** [comment]
Hi! Thanks for you pull request. Could you please amend  your commit to explain why this change was made. That way other contributors  will understand since this is a community project.

**Comment by achadwick** [comment]
The link should be a relative one if the intent is to read it in github

    [`mypaint.iss.in`](innosetup/mypaint.iss.in)

once this is fixed, no objection to merging.

**Comment by odysseywestra** [comment]
Okay, looks good, all that is left is that we need you to do is squash those two commits together into one commit and we should be golden.

**Comment by achadwick** [comment]
@odysseywestra
Github has grown a "Squash and merge" feature for people merging PRs. Looks like it'll do the right thing; I'll try it out here :smile:

**Comment by achadwick** [comment]
Looking good. Thanks, @daleathan! :tada:

**Pull request merged**
