### PR TITLE
Correctly handle PNG transparency when saving

### PR DESCRIPTION
**Pull request by jy2wong**
For issue #165. The parameter that governed whether or not blit_tile_into() kept the background in or not was inconsistently named (it was 'background' in half the source code, and 'render_background' in the other half). I suspect the regression made its way in because it's...nontrivial to keep track of all the parameters weaving in and out of kwargs/options on the way from gui/filehandling.py to lib/fastpng.hpp.

### CODE REVIEW

**Comment by achadwick** [comment]
The `SAVE_FORMAT_PNGAUTO` has a good, simple "Do What I See" nature. I like it.

Thanks for doing the detective work re. the parameters. Yeah, that API and parameter chain is an old horror that needs sorting out and/or documenting. One day.

Let me know if you want commit access, by the way. I can add you to @mypaint/collaborators.

**Comment by jy2wong** [comment]
Oops, I never noticed because the items showed up in the same order as before on my machine. That's certainly not something to rely on, though. And thanks for pointing me towards OrderedDict; I didn't know it was a thing. Anyway, this is fixed up now.

As for commit access, I wouldn't mind it, but I'd probably end up pull-requesting anything greater than 2 lines and/or possibly debatable anyway because I think it's generally good to have more than one set of eyeballs looking at incoming code.

**Comment by achadwick** [comment]
Invite sent. I'm happy to review things via PR always, but you may find team membership useful for just pushing oneliner fixes. I think (but I'm not sure) that you'll get the ability to merge PRs too.

**Comment by 0ion9** [comment]
@achadwick : Answer seems to be yes -- see https://help.github.com/articles/permission-levels-for-a-user-account-repository/ , various operations on PRs ,including merging, are on the list.

**Pull request merged**
