### PR TITLE
Generate and upload AppImage of each commit

### PR DESCRIPTION
**Pull request by probonopd**
This PR, when merged, will generate and upload an [AppImage](http://appimage.org/) of each commit. It does so by bundling MyPaint, Python, and the required Python modules inside the AppImage.

The URL of the AppImage can be found in the Travis CI build log, it is beginning with `http://bintray...`. Of course you can change this to use the GitHub Releases mechanism for hosting the binaries instead.

### CODE REVIEW

**Comment by achadwick** [comment]
Can you squash the changes to .travis.yml and the appimage script to make it a bit easier to read please? Thanks!

**Comment by probonopd** [comment]
Yes, unfortunately on GitHub the project receiving a PR but not the sender of a PR can use this function: https://github.com/blog/2141-squash-your-commits

**Comment by achadwick** [comment]
Senders can squash and force-push too, and the PR will automatically update from the branch.

**Comment by probonopd** [comment]
> Senders can squash and force-push too

How? That'd be great. Still downloading the source code of this repository...

**Comment by probonopd** [comment]
On Ubuntu 16.04:
```
strings /usr/lib/x86_64-linux-gnu/libgtk-3.so.0.1800.9 | grep gdk__private
gdk__private__
strings /usr/lib/x86_64-linux-gnu/libgdk-3.so.0.1800.9 | grep gdk__private
gdk__private__
```

**Comment by probonopd** [comment]
Giving up on the squashing, just doesn't seem to work for me (on the git command line)

**Comment by achadwick** [comment]
Like this: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

You can test it out in a trial branch with

```
git checkout -b throwaway_tmp
git rebase -i origin/master    # assuming the main repo is "origin"
```

In editor, mark all but 1st as "s" squash or "r" (reword), save, quit.

You *absolutely* need to include the libraries that Python needs, and also anything Gtkish our Python code pulls in over GObject-Introspection.

If you're including GdkPixbuf in the appimage (and you should), you will have to make sure that it always regenerates its cache with gdk-pixbuf-query-loaders. GLib will need to be told to recompile schemas too. There are presumably recipes out there for doing this for an AppImage!

If the AppImage kit examines binaries to determine their libs, a sneaky backdoor way of including them would be to include gtk3-demo - which has a really handy event axis tester built into it. It'd make it easier to debug and support the images. I _think_ if you can run that, you ought to be able to run MyPaint.

**Comment by probonopd** [comment]
Yes, and then I am always getting

```
To https://github.com/probonopd/mypaint.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/probonopd/mypaint.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by achadwick** [comment]
"Absolute" being a key term for gdk-pixbuf-query-loaders, and the paths it writes to its horrid little cache file... :stuck_out_tongue_closed_eyes:

You'll need to push with --force. Don't bother if you're still working in this branch; I can squash it myself later.

**Comment by probonopd** [comment]
> If you're including GdkPixbuf in the appimage (and you should)

Doing that [here](https://github.com/probonopd/mypaint/commit/5c247336014fa7815a917adadbebb462b2c3dc5a#diff-619fd214cd85adcb2b8854f40b8a6d79R70)

> you will have to make sure that it always regenerates its cache with gdk-pixbuf-query-loaders

I wasn't aware of this, what is it for? Can't remember having this done for any other AppImage so far.

> GLib will need to be told to recompile schemas too. There are presumably recipes out there for doing this for an AppImage!

Yes, indeed, e.g., [here](https://github.com/probonopd/AppImages/blob/85e3dbea930220eec0bad8db19ab2fd931fd2f4d/recipes/terminix/Recipe#L31).

> If the AppImage kit examines binaries to determine their libs, a sneaky backdoor way of including them would be to include gtk3-demo

That's a really cool idea! Like it!

**Comment by achadwick** [comment]
> I wasn't aware of this, what is it for? Can't remember having this done for any other AppImage so far.

MyPaint uses librsvg and the rsvg plugin for gdk-pixbuf to render its toolbar icons and its vector layers. Bonus achievement level for any aspiring appimage developer: allow an Inkscape or GIMP appimage to manage external layer edits in MyPaint!

**Comment by probonopd** [comment]
> Bonus achievement level for any aspiring appimage developer: allow an Inkscape or GIMP appimage to manage external layer edits in MyPaint!

I guess that'd be [Carmelo_DrRaw](https://discuss.pixls.us/t/gimp-2-9-5-appimage/1959) then ;-)

**Comment by probonopd** [comment]
@achadwick the latest one launches successfully on my Ubuntu 16.04 machine. Just the GTK theme is not correct.

Do you know which git command would give me the `1.3.0-alpha+git.00c7568` string?

**Comment by achadwick** [comment]
> Do you know which git command would give me the 1.3.0-alpha+git.00c7568 string?

We use

```sh
$ python2 lib/meta.py 
MYPAINT_VERSION_BASE='1.3.0-alpha'
MYPAINT_VERSION_FORMAL='1.3.0-alpha'
MYPAINT_VERSION_CEREMONIAL='1.3.0-alpha+gitexport.427c7e5'
$ eval `python2 lib/meta.py`
$ echo "long-version: $MYPAINT_VERSION_CEREMONIAL"
long-version: 1.3.0-alpha+gitexport.427c7e5
```

The results are good Python and Bourne Shell by design.

**Comment by achadwick** [comment]
(It's stuck at 1.2.0 because alpha development doesn't have a reasonable preceding tag. We don't make official releases during this period.)

**Comment by probonopd** [comment]
Can you take over from here? I think the remaining polish needs some domain knowledge about the application which I don't have.

**Comment by probonopd** [comment]
Ping @achadwick is anything missing from my side so this can be merged?

**Pull request merged**
