### PR TITLE
Add right click menu to brushes

### PR DESCRIPTION
**Pull request by jy2wong**
Starting with add to favourites, remove from favourites, copy, delete
and a placeholder for edit. I also noticed that the recently used list in the toolbar window doesn't respond to right clicks.

menu

This is a WIP that needs more testing. **use a separate throwaway config area for this. It was eating brush groups every launch until I fixed something, and I'm not totally convinced the code is bulletproof yet.**

Partial list of things that I've tried:
* copy brush, restart mypaint
* copy brush, copy its copy, restart mypaint
* copy brush, switch group, switch back, delete copy, restart mypaint
* delete brush, restart mypaint
* favourite brush, restart mypaint
* copy brush, favourite copy, delete copy, restart mypaint

Also would appreciate feedback on the naming of the menu options.

Addresses issue #229 .

### CODE REVIEW

**Comment by iirelu** [comment]
Thanks for working on this! This is *exactly* the kind of thing that was needed.

I noticed the "Edit brush" option is a placeholder, but already I can tell that it should be renamed to "Edit Brush Settings" for consistency with the Brush > Edit Brush Settings menu option.

"Add brush to favorites" is pretty broken, this is after adding one brush and then another three times:
b

Having the "brush" in all the descriptions is *super* redundant, "Add to favorites", "Remove from favorites", "Copy", "Edit", "Delete" should be used instead. Also, "Copy" usually indicates that something is being copied to the clipboard, which isn't what's happening. It should be renamed to "Clone". 

Again, thanks for starting to work on this!

**Comment by jy2wong** [comment]
Oops. I made sure the favourite callback functions caused a `brushes_changed` event on the right set of brushes, made only one of add/remove show up in the right click menu and renamed everything (in the edit brush dialog, "clone" is called "Copy to New". Should that be changed over to Clone as well?

**Comment by iirelu** [comment]
Thanks for the changes!

Hmm, didn't we used to have a "Trash" folder? I was thinking that instead of an outright delete, there could be a "Move to trash" option, followed by "Delete" and "Restore" when in the trash. Alternatively, we could add a confirmation dialog to the "Delete" button, as I can see that becoming a big issue for some.

Apart from that, this looks good from a functionality perspective! @achadwick, what do you think of the code?

**Comment by jy2wong** [comment]
Just as a sanity check, it's sensible to delete a brush from both favourites and the brush group it was in, yes?

**Comment by iirelu** [comment]
@jy2wong Hm, not really. "Clone" should probably go too, for brushes in the favourites. If a user wants to clone or delete something, they can do it from the original.

To the user, the favourites is a special folder that doesn't actually contain brushes, just links to brushes. Of course, it doesn't actually work that way, but that's the most comfortable way to picture it.

**Comment by jy2wong** [comment]
Yeah okay, sounds reasonable.

Also, thanks for putting up with all my silly UI questions. I've been using linux for years and have a...very high tolerance for bad UI decisions. :sweat:

**Comment by iirelu** [comment]
It's okay! Asking a silly question is better than making a silly mistake.

**Comment by jy2wong** [comment]
Left a86ebfe as a separate commit just to make it clear what's been changed; I'll smush it together with the main commit once everyone's happy.

**Comment by iirelu** [comment]
Frankly I much prefer a detailed commit history to a "clean" one, so you don't have to rebase.

Tested some more and this works great! Thanks for putting up with all my nagging, will merge this now!

**Pull request merged**
