### PR TITLE
Fix coordinates of the "object-unlocked" icon

### PR DESCRIPTION
**Pull request by danpla**
Before/after:
img

### CODE REVIEW

**Comment by achadwick** [comment]
I'd like to see what happens if we keep the body of the lock still, but reflect the shackle popping out.

**Comment by danpla** [comment]
Like in Krita?
2016-06-27-154115_1600x900_scrot

**Comment by odysseywestra** [comment]
This is a fairly simple fix. @achadwick are you okay with me Rebasing and Merging this one in?

**Comment by achadwick** [comment]
Yes, fine. Let's do that now, in fact. I've been putting this off because I quite like the body of the lock popping out like that, in a way.

We can always revert later on :)

**Pull request merged**
