### PR TITLE
Use the right bounding box when saving a file

### PR DESCRIPTION
**Pull request by danpla**
Currently, unless the frame is enabled, MyPaint saves files using an internal (dynamic) bounding box, which is always multiple by the tile size, and has (0, 0) coordinates. This is not the right way to do this. Let me explain using ORA as an example.

There are two backgrounds that MyPaint writes to ORA files:

* External, saved as a regular layer to be used by other software. This layer is just cropped using dimensions and coordinates of the dynamic bounding box. This can be OK when the background has no sensible borders (like a seamless canvas texture), but otherwise this is not what the user expects.

* Internal, to be used by MyPaint. This one has the right size (the size of the original image used as background), but since it's cropped from coordinates of the dynamic bounding box, it becomes completely broken (see issue #10).

From the user's point of view, in both cases MyPaint writes a corrupted ORA, because it's not possible to restore the previously used background image, neither in MyPaint (see #10) nor in any other software.

The user should not care about MyPaint internals (the tile size in this case).

For example, when I use `50_comicthumbs.png` for background, I expect that MyPaint will save the full frame, even if I drew something in the bottom right corner (or didn't draw anything at all). In other words, the final size of the saved image should always be multiple of the size of the background image.

### CODE REVIEW

**Comment by achadwick** [comment]
Liking this so far. It also makes Nautilus thumbnails for comics more understandable :+1: 

screenshot from 2016-06-08 00-45-13

**Comment by achadwick** [comment]
I would be testing with GIMP, but its ORA plugin is currently too broken to load *any* .ora file on my test machine. Bah. The offsets in `stack.xml` look Perfectly Reasonable to me at a first glance :smiley: 

Testing: I need to confirm that:

- [ ] Files saved with `user-bbox`still open and looking correct under the current master as of 8acacb3dd0d972371d8b0a97176e5a42d011b25f.
- [ ] Hand-hacked versions of a file saved with _user-bbox_ *without* a src attr on the background layer load OK in 
  - [ ] master as of 8acacb3dd0d972371d8b0a97176e5a42d011b25f
  - [ ] user-bbox
- [ ] Hand-hacked versions of a file saved with _user-bbox_ *relying only on* the src attr on the background layer load OK in
  - [ ] master as of 8acacb3dd0d972371d8b0a97176e5a42d011b25f
  - [ ] user-bbox

**Comment by achadwick** [comment]
All looks good. Thank you for closing this long-standing bug! :grinning:

**Comment by 0ion9** [comment]
@achadwick: too broken to load any ora, really? I've been working with a version of file-openraster.py that simply has one line added to load_ora(): `img.layers[-1].set_offsets(0,0)` (just before `return img`). That's been working quite well, I guess I'll have to remove it now.

**Comment by danpla** [comment]
@0ion9 On my machine:
```python
Traceback (most recent call last):
  File "/usr/lib/gimp/2.0/python/gimpfu.py", line 851, in _run
    res = apply(func, params[1:])
  File "/usr/lib/gimp/2.0/plug-ins/file-openraster.py", line 274, in load_ora
    if not name:
UnboundLocalError: local variable 'name' referenced before assignment
```
This has been fixed in the GIMP's master branch.

**Pull request merged**
