### PR TITLE
inktool user interface improvement

### PR DESCRIPTION
**Pull request by dothiko**
First of all,I'm very new to github and opensource development.furthermore,my native language is Japanese,not English.so if I did something wrong,please excuse me.

by the way,I wrote some codes for inktool interface improvement.

* delete currently selected node from keyboard(Gtk.Action)
* simplify (delete) inktool nodes which is too close to others or near straight.
* cull inktool nodes alternately.
* modify pressure of  currently targeted node with scroll wheel event. when pointer is off from inktool node(=there is no targetted node),scroll wheel can be used as view controller as usual.

for your convinience,I uploaded a short demo movie to youtube.
https://youtu.be/Lwc11-3SDMc

Thanks.

### CODE REVIEW

**Comment by tumagonx** [comment]
for line-simplification, there are several well know algorithms such douglas-pecker or reumann-witkam

**Comment by achadwick** [comment]
Changing pressure with the scroll wheel is a fantastic idea. Thank you for the contribution!

There are extra actions in these commits, with new translatable strings, so sadly this can't go in before 1.2.0 is released. Program translations are currently frozen: I made a promise to our translators to keep things static while the release is being finalized.

Scheduled for very early in the 1.2.1 development phase. I may ask you to squash and rebase against master when the 1.2.0 release is out.

**Comment by dothiko** [comment]
@tumagonx : Thanks,I googled them and tried rewriting simplify routine with reumann-witkam algorithm.
I'm not sure I could correctly implemented that algorithm,but I can get much better result...

@achadwick : Thanks,I understand it.I'm looking forward to 1.2.1.

**Comment by achadwick** [comment]
@dothiko
I've rethought the versioning strategy and our milestones: this is assigned to 1.3.0 now (by rename of milestone), because it is a new feature. v1.2.1 will collect bugfixes for 1.2.0 only. Sorry for the confusion!

The problem was my fault, a misunderstanding of [SemVer](semver.org).

**Comment by achadwick** [comment]
@dothiko 
Quickly reviewing this as of 8939d91f8b6cec11bf60014c006c7c3a8025b4ae. It's looking good!

* Please can you add a commit on top that updates brushlib to the version in `master`. Alternatively, please use `git rebase` and splits to take changes to it out of your branch's history completely? Thanks.
* There seems to be a spurious change to gui.filehandling. Can you rebase+split it out please?
* The Cull Points and Simplify Points buttons cannot be clicked until a node is selected.
* I can't get the scrollwheel functionality to work. When I point at at a node and scroll my mouse wheel, I do not get any change. The pressure does not change whether or not I first clicked on the node.

I'll add some line comments too. I think they'll be visible in this PR thread while the timeline is consistent.

**Comment by dothiko** [comment]
@achadwick  Thank you so much for reviewing my codes!
I seriously need inktool's node manipulate function to draw anime-like lineart.Inktool is very useful for it!

> I've rethought the versioning strategy and our milestones: this is assigned to 1.3.0 now (by rename of milestone), because it is a new feature. v1.2.1 will collect bugfixes for 1.2.0 only. Sorry for the confusion!

I understand , I think it would be a good idea to make mypaint more polished!

I've also written and still tested another branch , which enables to edit a node pressure by dragging pointing device(mouse or pen-tablet stylus) with holding shift key. 
I think this would be very useful when using pen tablet.

> The Cull Points and Simplify Points buttons cannot be clicked until a node is selected.

I confirmed this issue, and fixed it.
I'm still not familiar with git, so I'll deal with git related problems (rebase/split it off/squash) later.sorry.
Or,should I push fixed code prior to rebase?

> I can't get the scrollwheel functionality to work. When I point at at a node and scroll my mouse wheel, I do not get any change. The pressure does not change whether or not I first clicked on the node.

I cannot confirm this problem...and In my pc,any of my mice work well,so it does not seems to be device specific issue.

for your convenience,my environment is,
OS: Ubuntu Linux 14.04.3 LTS 
Mouse : Logitech M100 / M570 /M325 , Toshiba IPC5017A  (each of them works fine)
Window Manager : xfce 4.10
X.Org X Server 1.16.0
xev tells mouse wheel as button 4(up) and 5(down),in my environment.

**Comment by 0ion9** [comment]
@dothiko :

> I've also written and still tested another branch , which enables to edit a node pressure by dragging pointing device(mouse or pen-tablet stylus) with holding shift key.
> I think this would be very useful when using pen tablet.

Definitely! I'm happy about this, and will test it, because although I have a mouse, I never use it -- I do everything via tablet. Wheel events are only generated when I remember my mouse exists, haha.

> I'm still not familiar with git, so I'll deal with git related problems (rebase/split it off/squash) later.sorry.
> Or,should I push fixed code prior to rebase?

When doing a forced push, this doesn't matter AFAIK; you can push whenever you want. I would recommend only pushing when you've confirmed the code is in a working state, but that's just a guideline to minimize confusion.

**Comment by achadwick** [comment]
> > I've also written and still tested another branch , which enables to edit a node pressure by dragging pointing device(mouse or pen-tablet stylus) with holding shift key.

Would a system like the colour adjusters would be useful here. When you drag button2 button over the HCY wheel, or the left side of the before/after pair in the bottom left of the main window, it adjusts the current colour's luma up and down, making it lighter or darker. Could that be used on a node to tweak its pressure?

**Comment by dothiko** [comment]
Thanks, @0ion9 

> I do everything via tablet. 

now me too!
I noticed this drawing/painting style much more comfortable than switching between mouse and tablet,after created this branch...

> When doing a forced push, this doesn't matter AFAIK; you can push whenever you want. I would recommend only pushing when you've confirmed the code is in a working state, but that's just a guideline to minimize confusion.

Thanks,finally I managed to rebase initial commit of this branch,and I'll push it with GUI(and some codes) fix after confirm the code works correctly.

**Comment by dothiko** [comment]
> Would a system like the colour adjusters would be useful here? When you drag button2 over the HCY wheel, or the left side of the before/after pair in the bottom left of the main window, it adjusts the current colour's luma up and down, making it lighter or darker. Could that be used on a node to tweak its pressure?

Yes,this HCL wheel interface (decrease up/left, increase down/right) is mostly same as  how I use to implementing on-canvas pressure manipulation.
but, button2 activates context menu on canvas , and button2 is somewhat hard to use with pen stylus,so I use button1.

Currently, the way of pressure manipulation of my code is,

1.  set pointer upon a node. because if pointer is off from a node when start dragging,inktool enters another capture phase,so we need to place pointer on a node.
1.  holding shiftkey and drag (up or left)/(down or right)
1.  the selected node's pressure decreased/increased ,instead of changing the node position.

**Comment by dothiko** [comment]
I reconsidered and decided split scroll wheel codes off from this branch,because it seems to be  difficult for me to resolve at this time,and that feature has a thin relevant to this branch.
I'll continue to develop it along with hold-and-modify feature at [inktool_pressure_edit_oncanvas](https://github.com/dothiko/mypaint/tree/inktool_pressure_edit_oncanvas) branch.

and I've noticed that I gave wrong name this branch...it must be 'inktool UI mod' or something...

**Comment by achadwick** [comment]
There were still some unnecessary merges and code additions then removals still in this set of patches, so I've squashed and rebased. I've left bugfixes intact, but squashed out some whitespace-only fragments.

The timeline's still a bit messy, but it's tolerable to me now. I've left your authorship intact, but of course it's a divergent timeline now.

Thanks for this awesome new feature, and sorry to be so fussy about the code :smile:

**Comment by dothiko** [comment]
Thanks, @achadwick , I appreciate your hard work.
I'm so sorry to have troubled you,especially from my lack of experience for git/github and mypaint development.
I will be more careful in future.

**Comment by achadwick** [comment]
@dothiko It's no trouble. Tidying and refining patches is fairly natural to me now, but it took me a while to learn too. I should probably write up a "how we git" page on the wiki, but I'm aware that I'd break any rule I write myself almost straight away. Better to treat the learning as a conversation, and let shared practice evolve in its own time :blush:

Is there anything we could add to <https://github.com/mypaint/mypaint/wiki/Contributing-Patches>?

For what it's worth, I use `git gui` to make almost all commits now. Being able to divide up a big diff into lots of small, logical changes with the mouse is surprisingly nice :open_mouth: 
I normally refine and tidy my own branches with `git rebase -i` before pushing. One reason for that is getting the [commit messages](https://github.com/mypaint/mypaint/wiki/Contributing-Patches#commit-messages) right: Vim has great syntax highlighting.
Also recommended: `gitk`. It's a very handy tool for visualizing branch history and figuring out, for example, exactly which commits hit a single method.

Thank you so much for investigating the fancy curve simplification algorithm and coming up with a good implementation. There's some smart higher-order function stuff going on in there that makes a lot of sense for the global ops.

For future work, I might consolidate the buttons in the options panel to an "inline-toolbar" style toolbar with icons. There are currently 4 button actions, and people want more!

**Comment by achadwick** [comment]
Sorry, reopened in error. Blame slow coffee shop wifi!

**Pull request closed without merging**
