### PR TITLE
Update windowing.py to GTK 3.24

### PR DESCRIPTION
**Pull request by AesaraB**
Part of #1211

Depreciated GDK references:
```
./windowing.py:222:	self._align = Gtk.Alignment.new(0.5, 0.5, 1.0, 1.0)
./windowing.py:266:	grab_status = device.grab(
./windowing.py:284:	device.ungrab(time_=time)
./windowing.py:291:	screen = event.get_screen()
./windowing.py:292:	mon = screen.get_monitor_at_point(event.x, event.y)
./windowing.py:293:	mon_geom = screen.get_monitor_geometry(mon)
./windowing.py:326:	w = win.get_width()
./windowing.py:327:	h = win.get_height()
./windowing.py:724:	screen = win.get_screen()
./windowing.py:726:	devmgr = display and display.get_device_manager() or None
./windowing.py:727:	ptrdev = devmgr and devmgr.get_client_pointer() or None
./windowing.py:741:	screen_w = screen.get_width()
./windowing.py:742:	screen_h = screen.get_height()
./windowing.py:747:	targ_mon_num = screen.get_monitor_at_point(ptr_x, ptr_y)
./windowing.py:759:	for mon_num in xrange(screen.get_n_monitors()):
./windowing.py:801:	This function operates like gdk_screen_get_monitor_geometry(), but
./windowing.py:812:	geom = screen.get_monitor_geometry(mon_num)
./windowing.py:817:	"gdk_screen_get_monitor_geometry() returned NULL: "
./windowing.py:820:	geom = Rect(0, 0, screen.get_width(), screen.get_height())
```
I haven't checked GTK API references, though.

### CODE REVIEW

**Comment by AesaraB** [comment]
#1161 Replaced ``Gdk.Device.grab()`` (deprecated) with ``Gdk.Seat.grab()``.

New problem is line 238, ``inside = (x <= event.x_root < x+w) and (y <= event.y_root < y+h)`` only seems to report False.

**Comment by odysseywestra** [comment]
Okay, do you want me to merge this PR into gtk-4.0 branch?

**Comment by AesaraB** [comment]
This is still a draft. It partially fixes the relevant issues, but I'd like to focus on other issues (new directory structure, upgrading build system, upgrading unit tests) before merging this one in.

The lack of this feature breaks MyPaint on Wayland compositors, so it is important to finish this draft before v2.1.0

**Comment by jtojnar** [comment]
> Okay, do you want me to merge this PR into gtk-4.0 branch?

In other projects that were migrated to GTK 4, we often incrementally update the deprecations for minor GTK version upgrades in small, self-contained, easy-to-review PRs and target them directly to the development branch once they are ready. As they are self-contained, they should not affect the functionality of the rest of the app (at most we will need to bump minimal GTK version, which should be fine for development branch) so this will reduce divergence between GTK 4 branch and develoment branch, making it in turn easier to review and rebase onto master.

**Comment by AesaraB** [comment]
@jtojnar I will ask, thanks to PyGI's (and Python's) fun way of calling methods I have trouble finding all the depreciated calls to begin with. Do you know of a way to find them quickly?

**Comment by jtojnar** [comment]
Yeah, this is much easier with compiled languages. Here we can only see the deprecations through at runtime.

But you should not need to switch to GTK 4, you should be able to enable the deprecation warnings ([silenced by default](https://gnome.pages.gitlab.gnome.org/pygobject/guide/api/api.html#gi.PyGIDeprecationWarning)) with the following patch:

```patch
--- a/mypaint.py
+++ b/mypaint.py
@@ -26,6 +26,9 @@ import os.path
 from os.path import join, isdir, dirname, abspath
 import re
 import logging
+import warnings
+import gi
+warnings.simplefilter('default', gi.PyGIDeprecationWarning)
 
 logger = logging.getLogger('mypaint')
 if sys.version_info >= (3,):
```

There are also some deprecations which need to be enabled with `G_ENABLE_DIAGNOSTIC=1` as per the [migration guide](https://docs.gtk.org/gtk4/migrating-3to4.html#enable-diagnostic-warnings).

(Though for some reason I am not getting all the warnings I would expect.)

---

There was a [feature request](https://github.com/python/mypy/issues/2403) for mypy to find deprecations using static analysis but it fizzled out due to a lack of standard deprecation markings. Looks like those has been accepted since in [PEP-0702](https://peps.python.org/pep-0702/) but it will take time until they are recognized by tooling. And since we do not do static analysis currently, we would need to [start first](https://mypy.readthedocs.io/en/stable/getting_started.html). Also since the bindings are generated at runtime, we would need to employ https://github.com/pygobject/pygobject-stubs/issues/165.

**Comment by jtojnar** [comment]
Quoting Neui from the GNOME Python chat:

> Use [Python Development mode](https://docs.python.org/3/library/devmode.html) which shows `DeprecationWarning` globally ([default](https://docs.python.org/3/library/warnings.html#default-warning-filter) is to hide them except `__main__`). PyGObject [uses](https://gitlab.gnome.org/GNOME/pygobject/-/blob/9b9f87d99f4f22681fbfaf22700e63c935c7bcd5/gi/pygi-cache.c#L732) the Python `DeprecationWarning` for deprecated library stuff instead of the PyGObject-specific `PyGIDeprecationWarning` used by PyGObject specific overrides and stuff (it seems, from reading the code). This is what it looks like with `Gtk.Alignment.new` for example:
> 
> ```
> test-deprecation.py:7: DeprecationWarning: Gtk.Alignment.new is deprecated
>   alignment = Gtk.Alignment.new(1, 1, 1, 1)
> ```

**Comment by AesaraB** [comment]
@jtojnar Could you copy your previous messages to #1211? It's really good information to have on hand, but the scope of this draft is just to update windowing.py (or more realistically, fix it just enough to get wayland compositors working for popup windows)

**Comment by AesaraB** [comment]
wait, I have fingers don't I? I'll do it

**Pull request closed without merging**
