### PR TITLE
Revert the patch on libgtk so that it loads themes from the system

### LINKED ISSUE #829: Appimage: Apply a Theme to Interface
One thing that has been bugging about the MyPaint appimage is the lack of the Adwaita Theme applied. Right now it use a really ugly theme though it is functional. @probonopd is there a way to apply the Adwaita Theme or a way for it to use the system theme?

### PR DESCRIPTION
**Pull request by probonopd**
Closes #829, discussion there.

### CODE REVIEW

**Comment by odysseywestra** [comment]
Got an error while trying to launch...
```
[albert@Helios Downloads]$ ./MyPaint-1.3.0-git.1a513bc.glibc2.15-x86_64.AppImage 
zenity, kdialog, Xdialog missing. Skipping /tmp/.mount_MyPainp4jMLp/usr/bin//mypaint.wrapper.
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/tmp/.mount_MyPainp4jMLp/usr'
INFO: lib.i18n: POSIX: LANG='en_US.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE=None

** (process:10877): WARNING **: Failed to load shared library 'libgtk-3.so.0' referenced by the typelib: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

** (process:10877): WARNING **: Failed to load shared library 'libgdk-3.so.0' referenced by the typelib: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
Traceback (most recent call last):
  File "/tmp/.mount_MyPainp4jMLp/usr/bin/mypaint", line 464, in <module>
    from gui import main
  File "/tmp/.mount_MyPainp4jMLp/usr/lib/mypaint/gui/main.py", line 22, in <module>
    from gi.repository import Gtk
  File "/tmp/.mount_MyPainp4jMLp/usr/lib/python2.7/dist-packages/gi/importer.py", line 68, in load_module
    dynamic_module._load()
  File "/tmp/.mount_MyPainp4jMLp/usr/lib/python2.7/dist-packages/gi/module.py", line 296, in _load
    self._overrides_module = importlib.import_module('gi.overrides.' + self._namespace)
  File "/tmp/.mount_MyPainp4jMLp/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/tmp/.mount_MyPainp4jMLp/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 75, in <module>
    class Widget(Gtk.Widget):
  File "/tmp/.mount_MyPainp4jMLp/usr/lib/python2.7/dist-packages/gi/module.py", line 183, in __getattr__
    interfaces = tuple(interface for interface in get_interfaces_for_object(info)
  File "/tmp/.mount_MyPainp4jMLp/usr/lib/python2.7/dist-packages/gi/module.py", line 109, in get_interfaces_for_object
    interfaces.append(getattr(module, name))
  File "/tmp/.mount_MyPainp4jMLp/usr/lib/python2.7/dist-packages/gi/module.py", line 320, in __getattr__
    return getattr(self._introspection_module, name)
  File "/tmp/.mount_MyPainp4jMLp/usr/lib/python2.7/dist-packages/gi/module.py", line 222, in __getattr__
    wrapper = metaclass(name, bases, dict_)
  File "/tmp/.mount_MyPainp4jMLp/usr/lib/python2.7/dist-packages/gi/types.py", line 221, in __init__
    register_interface_info(cls.__info__.get_g_type())
TypeError: must be an interface
```

**Comment by probonopd** [comment]
Aaaarrrggggghhhh. I changed the bundled libgtk to load themes from the system. Now that it does this, some themes want to use libharfbuzz.so.0, which seemingly want another version of libgtk-3.so.0.

That's probably why they say that Gtk+ 3 is not ABI mature yet...

**Comment by odysseywestra** [comment]
You know, I think for now it might be best to containerize all of GTK and use the default Adwaita theme for now. Yeah the appimage will be bigger, but I rather have stability over connivent aesthetics. We can worry about that later.

**Comment by probonopd** [comment]
Sure, that's a way to do it. Especially since Gtk+ 3 (as currently shipped by LTS distros) still seems to be a moving target rather than a stable platform with reliable frozen ABI.

**Comment by achadwick** [comment]
Yes, that's the approach I have been taking with the Windows bundles. The Adwaita icons are part of the theme (some of them, see the styrene .conf file), and the theme needs to match the GTK.

Assume I don't need to merge this PR. Please reopen if it's otherwise ☺

**Pull request closed without merging**
