### PR TITLE
patch for issue #544: blink in layer solo

### PR DESCRIPTION
**Pull request by arrouan**
small change to avoid a blink in layer solo mode

### CODE REVIEW

**Comment by achadwick** [comment]
Thanks for taking a look at this.

I'll have a look at this for the upcoming bugfix release as well as on master. It doesn't add any new features or string changes, so it's a good fit.

@arrouan, do you need to make any more changes here? There are a few trailing spaces in the commit that I don't much like, but they'd be easy for me to fix up while still giving you proper attribution for the contribution.

**Comment by arrouan** [comment]
I won't make any more changes on this issue, so feel free to add/remove whatever you want

**Comment by achadwick** [comment]
No problem, and thanks for the fix :smiley:

**Comment by achadwick** [comment]
Merged (with a few whitespace fixes) in b7e59eb0c2a1117030d48e28876dee58275a85ba.

**Comment by arrouan** [comment]
thank _you_, you actually handled everything in this process..

**Pull request closed without merging**
