### PR TITLE
Hsv Cube Circle for issue #268

### PR DESCRIPTION
**Pull request by ShadowKyogre**
This was coded to help out with issue #268. I use the triangle picker a lot myself, so I wanted to help out with this. Most of the aesthetics are worked out, but, there a few things of note that I think I should do:

* Maybe take the Hue ring slider and make a generic version of that?
* Strip out all the stuff I commented while working on a copy of the HSV Cube slice code.
* Cleanup the code now that the main concept is down and working. I'm sure that the code is super messy, so any additional help on how I can clean up the code's appreciated

### CODE REVIEW

**Comment by iirelu** [comment]
To be clear, you're attempting to make a replacement for the in-built GTK colour selector by building off of Mypaint's HSV cube selector?

Looks alright for the time being! Are you aiming to make the middle square a triangle?

b

**Comment by ShadowKyogre** [comment]
Yup! I might make it into a triangle, but when I asked @achadwick about it on IRC (Before I started working on the replacement), he said he prefers a square in circle one more since there doesn't have to be as much widget redrawing.

On May 10, 2015, Anna Harren <notifications@github.com> wrote:
>To be clear, you're attempting to make a replacement for the in-built
>GTK colour selector by building off of Mypaint's HSV cube selector?
>
>Looks alright for the time being! Are you aiming to make the middle
>square a triangle?
>
>b
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mypaint/mypaint/pull/315#issuecomment-100612656

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by achadwick** [comment]
Looks great so far! A few remarks:

* It's not responding to the choice of colour wheel primaries: see #266 for a request about that.
* The title of the popup is still "HSV Cube", and the tab tooltip details are wrong too.
* Can we rename it to HSV Square for consistency with the other widgets?
* (Once the name is decided) are you able to add an icon for the sidebar docker version and its tab tooltip? Generally I write little bits of code to make them - see the sliders widget for an example!
* Can you make it accessible from the colour selector dropdown in the toolbar please?
* Should the circle be the same width as the sliders in the RGB/HCY sliders page regardless of scale?

**Comment by ShadowKyogre** [comment]
@achadwick: Responses to each of the bullets

1. It is, buuut, the weird thing is that it isn't reapplying the layout (MyPaint needs a restart) for the primaries after the selection is done. Got a screenie that showcases the weirdness that's appropriately labeled.

&nbsp;
What I also noticed is that the GUI for the primaries selection isn't updating properly to reflect the actual choice between configuration saves even though the configuration's writing the right value.
&nbsp;
2. I know, I was focusing on getting the widget down before I wanted to give it a new name.
3. Sure thing! I'll go ahead and rename it in the appropriate places.
4. I should be able to! :D I'll get to work on that.
5. Commit https://github.com/ShadowKyogre/mypaint/commit/6cc45d780882ae2b6bfc0d919b7cdfbcdc861795 should've introduced this. Try rebuilding the development copy since it was doing that for me.
6. It should be. Is it not?

**Comment by ShadowKyogre** [comment]
All right, I got almost everything done except for making the proper icon for the HSV square in wheel. What happens when I try running the file by itself to generate the icon is this:

```
 _____/[shadowkyogre@AlpheTerra|2015-05-10 15:42:33]\______________)                                                                                                                                                               
(_/[~/b/mypaint]\_____________/((hsv-cube-circle)>--< python2 gui/colors/hsvsquare.py desktop/icons
Traceback (most recent call last):
  File "gui/colors/hsvsquare.py", line 13, in <module>
    from gui import gtk2compat
ImportError: No module named gui
```

This is what happened when I tried doing the same for the sliders icon to see what I should expect when generating the icons.
```
 _____/[shadowkyogre@AlpheTerra|2015-05-10 15:38:47]\______________)                                                                                                                                                               
(_/[~/b/mypaint]\_____________/((hsv-cube-circle)>--< python2 gui/colors/sliders.py desktop/icons

(sliders.py:11362): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:62:14: Theming engine 'unico' not found
Traceback (most recent call last):
  File "gui/colors/sliders.py", line 17, in <module>
    from lib.color import *
ImportError: No module named lib.color
```

**Comment by achadwick** [comment]
Ah! Typically I do something like

    $ cd path/to/mypaint
    $ PYTHONPATH=. python gui/colors/sliders.py

to run those little self-test and utility fragments.

**Comment by achadwick** [comment]
As for the auto-update of wheel type, looks like `gui.colors.adjbases.ColorManager.set_wheel_type()` gets called from the prefs windows to do the update job, and just tells all the adjusters to update their background (causing a full redraw). I don't like the `isinstance()` test in there, so that could be dropped.

It's up to individual wheel or circle adjusters to draw themselves appropriately, but their central colour manager knows how to `distort_hue()` and `undistort_hue()`. I guess you've figured that out though.

**Comment by ShadowKyogre** [comment]
Got the icons generated now! Only the svg one looks a little...weird. Not sure what's causing that in the generation code, but it's best viewed here to see the odd alpha dips in the middle of the square: https://github.com/ShadowKyogre/mypaint/blob/a129cdac4871e0fbf1b61239cc6f775de6203e5d/desktop/icons/hicolor/scalable/actions/mypaint-tool-hsvsquare.svg

**Comment by achadwick** [comment]
The scalable icon can be safely deleted - they generally don't do well due to the kinds of hack we use for aligning things to pixels and drawing slices and wedges to make the draws quicker.

**Comment by ShadowKyogre** [comment]
All right, everything should be good to pull in now!

**Comment by achadwick** [comment]
> 6. It should be. Is it not?
￼
Ah, no. If you make the "C" popup huge, the edge scales up.

It's not really a big deal though, I guess.

**Comment by achadwick** [comment]
> 5. Commit ShadowKyogre@6cc45d7 should've introduced this. Try rebuilding the development copy since it was doing that for me.

I still get 

colsel-dropdown

and I don't see it listed in gui/toolbar.xml - that should be all that's needed :)

**Comment by achadwick** [comment]
(Apologies for the quoted number screwups above (fixed), and for me being slow at checking this patch over generally.)

**Comment by ShadowKyogre** [comment]
@achadwick: It's all right + Huh, I missed that dropdown. Let me go add it there too.

**Comment by achadwick** [comment]
Thanks for that; merged!

**Pull request merged**
