### PR TITLE
Format codebase with black

### PR DESCRIPTION
**Pull request by jtojnar**
It is already enforced by Hound on our CI.

### CODE REVIEW

**Comment by AesaraB** [comment]
I'll get on this and your other review requests this Friday, thanks for your work

**Review by AesaraB — APPROVED** [review]
LGTM, merging

**Comment by jtojnar** [comment]
Thanks.

Though for the future, it is generally better not to squash formatting changes with other fixes since they will obscure history archaeology commands like `git blame`. See also https://dev.to/this-is-learning/the-power-of-atomic-commits-in-git-how-and-why-to-do-it-54mn, https://www.aleksandrhovhannisyan.com/blog/atomic-git-commits/, https://gitdeveloperguide.solomonmarvel.com/git-best-practices-and-tips/atomic-commits-in-git-and-its-benefits-for-software-teams or https://curiousprogrammer.dev/blog/why-i-create-atomic-commits-in-git/

**Comment by AesaraB** [comment]
Ah, I see. I'll keep that in mind for next time

**Pull request merged**
